version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: ordermeow_rabbit
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_DEFAULT_VHOST=ordermeow
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq:/var/lib/rabbitmq  
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:15
    container_name: ordermeow_postgres
    environment:
      - POSTGRES_DB=ordermeow_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: ordermeow_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  
  prometheus:
    image: prom/prometheus:latest
    container_name: ordermeow_prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./monitoring/prometheus.yml.template:/etc/prometheus/prometheus.yml.template:ro
      - prometheusdata:/prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - postgres
      - redis
    
  grafana:
    image: grafana/grafana:latest
    container_name: ordermeow_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports: 
      - 3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  rabbitmq:
  pgdata:
  redisdata:
  prometheusdata:
  grafanadata: